[package]
name = "accounts-provider-google"
version = "0.1.0"
edition = "2024"
description = "Google provider process for Accounts for COSMIC"

[dependencies]
accounts = { path = ".." }
zbus = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "accounts-provider-google"
path = "src/main.rs"
